"""
Flask backend for Baltimore Air Quality visualization dashboard.
Run with: python app.py
"""

from flask import Flask, render_template, send_from_directory, jsonify, Response
import folium
import glob
import math
import os
import pandas as pd

from src.fetch_emissions import get_emissions_df, get_ghg_df, EMISSIONS_DATA
from src.config import NEIGHBORHOODS, WHEELABRATOR, DATA_DIR
from src.presentation import get_presentation_context

app = Flask(
    __name__,
    template_folder="templates",
    static_folder="output",
)

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
PRESENTATION_ASSETS_DIR = os.path.join(os.path.dirname(__file__), "presentation_assets")


def discover_monitor_charts():
    """Scan output/ for per-monitor HTML files generated by the analysis pipeline."""
    monitors = {}
    for path in glob.glob(os.path.join(OUTPUT_DIR, "pollution_rose_*.html")):
        basename = os.path.basename(path)
        # Extract the site label, e.g. "39.29_-76.47" from "pollution_rose_39.29_-76.47.html"
        label = basename.replace("pollution_rose_", "").replace(".html", "")
        monitors[label] = {"label": label}

    # Attach whichever related files exist for each monitor
    for label in monitors:
        monitors[label]["pollution_rose"] = f"pollution_rose_{label}.html"
        for chart_type in ["directional", "timeseries", "seasonal"]:
            fname = f"{chart_type}_{label}.html"
            if os.path.exists(os.path.join(OUTPUT_DIR, fname)):
                monitors[label][chart_type] = fname

    return monitors


@app.route("/")
def index():
    """Dashboard landing page with all visualizations."""
    emissions_df = get_emissions_df()
    ghg_df = get_ghg_df()

    e2017 = {r["pollutant"]: r for _, r in emissions_df[emissions_df["year"] == 2017].iterrows()}
    e2014 = {r["pollutant"]: r for _, r in emissions_df[emissions_df["year"] == 2014].iterrows()}

    monitors = discover_monitor_charts()

    context = {
        "facility": WHEELABRATOR,
        "neighborhoods": NEIGHBORHOODS,
        "emissions_2017": e2017,
        "emissions_2014": e2014,
        "ghg_2017": ghg_df[ghg_df["year"] == 2017].iloc[0]["co2e_metric_tons"],
        "total_lbs_2017": sum(EMISSIONS_DATA[2017].values()),
        "total_lbs_2014": sum(EMISSIONS_DATA[2014].values()),
        "monitors": monitors,
    }
    return render_template("index.html", **context)


@app.route("/presentation")
def presentation():
    """Presentation-style page with copy-ready text and images."""
    context = get_presentation_context()
    chart_lookup = discover_monitor_charts()
    interactive_monitors = []
    for row in context.get("monitor_summary", []):
        raw = chart_lookup.get(row["chart_label"], {})
        charts = {}
        for key, value in raw.items():
            if key == "label":
                charts[key] = value
            else:
                charts[key] = f"/output/{value}"
        interactive_monitors.append({**row, "charts": charts})
    context["interactive_monitors"] = interactive_monitors
    return render_template("presentation.html", **context)


@app.route("/emissions")
def emissions():
    """Facility emissions chart."""
    return send_from_directory(OUTPUT_DIR, "facility_emissions.html")


@app.route("/emissions-trace")
def emissions_trace():
    """Trace pollutant emissions chart."""
    return send_from_directory(OUTPUT_DIR, "facility_emissions_trace.html")


@app.route("/output/<path:filename>")
def serve_output(filename):
    """Serve any file from the output directory."""
    return send_from_directory(OUTPUT_DIR, filename)


@app.route("/presentation-assets/<path:filename>")
def serve_presentation_assets(filename):
    """Serve generated presentation PNGs."""
    return send_from_directory(PRESENTATION_ASSETS_DIR, filename)


@app.route("/wind-rose")
def wind_rose():
    """Overall wind rose image."""
    return send_from_directory(OUTPUT_DIR, "wind_rose.png")


@app.route("/wind-rose/<season>")
def wind_rose_season(season):
    """Seasonal wind rose images."""
    allowed = {"winter", "spring", "summer", "fall"}
    if season not in allowed:
        return "Not found", 404
    return send_from_directory(OUTPUT_DIR, f"wind_rose_{season}.png")


def _haversine_km(lat1, lon1, lat2, lon2):
    R = 6371
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat/2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2)**2
    return R * 2 * math.asin(math.sqrt(a))


def _nearest_neighborhood(lat, lon):
    """Return the name of the closest neighborhood to a lat/lon point."""
    best_name, best_dist = None, float("inf")
    for name, info in NEIGHBORHOODS.items():
        d = _haversine_km(lat, lon, info["lat"], info["lon"])
        if d < best_dist:
            best_dist = d
            best_name = name
    return best_name, best_dist


def _load_monitor_locations():
    """Load unique AQS monitor locations from cached CSV if available."""
    path = os.path.join(DATA_DIR, "aqs_monitors.csv")
    if not os.path.exists(path):
        return []
    df = pd.read_csv(path)
    if "latitude" not in df.columns or "longitude" not in df.columns:
        return []
    unique = df.drop_duplicates(subset=["latitude", "longitude"])[["latitude", "longitude"]]
    monitors = []
    for _, row in unique.iterrows():
        name, dist = _nearest_neighborhood(row["latitude"], row["longitude"])
        monitors.append({
            "lat": row["latitude"],
            "lon": row["longitude"],
            "nearest": name,
            "dist_km": round(dist, 1),
        })
    return monitors


@app.route("/study-map")
def study_map():
    """Map showing study neighborhoods and AQS monitor locations."""
    m = folium.Map(location=[39.28, -76.60], zoom_start=10, tiles="CartoDB positron")

    colors = {
        "both": "#ef4444",
        "i95": "#f59e0b",
        "control": "#6b7280",
    }

    for name, info in NEIGHBORHOODS.items():
        if info["near_wheelabrator"] and info["near_i95"]:
            group = "both"
            tag = "Near Wheelabrator & I-95"
        elif info["near_i95"]:
            group = "i95"
            tag = "I-95 Corridor Only"
        else:
            group = "control"
            tag = "Control Area"

        folium.CircleMarker(
            location=[info["lat"], info["lon"]],
            radius=9,
            color=colors[group],
            fill=True,
            fill_color=colors[group],
            fill_opacity=0.7,
            popup=f"<b>{name}</b><br>{tag}",
            tooltip=name,
        ).add_to(m)

    # Wheelabrator marker
    folium.Marker(
        location=[WHEELABRATOR["lat"], WHEELABRATOR["lon"]],
        popup=f"<b>{WHEELABRATOR['name']}</b><br>{WHEELABRATOR['address']}",
        tooltip="Wheelabrator Baltimore",
        icon=folium.Icon(color="darkred", icon="industry", prefix="fa"),
    ).add_to(m)

    # AQS monitor locations (blue)
    aqs_monitors = _load_monitor_locations()
    for mon in aqs_monitors:
        folium.CircleMarker(
            location=[mon["lat"], mon["lon"]],
            radius=7,
            color="#3b82f6",
            fill=True,
            fill_color="#3b82f6",
            fill_opacity=0.8,
            popup=f"<b>EPA AQS Monitor</b><br>{mon['lat']:.4f}, {mon['lon']:.4f}<br>Nearest: {mon['nearest']} ({mon['dist_km']} km)",
            tooltip=f"AQS Monitor (near {mon['nearest']})",
        ).add_to(m)

    # Legend
    legend = """
    <div style="position:fixed; bottom:30px; left:30px; z-index:1000;
                background:white; padding:10px 14px; border-radius:8px;
                border:1px solid #ccc; font:13px/1.6 sans-serif;">
        <b>Study Areas</b><br>
        <i class="fa fa-industry" style="color:#8b0000"></i> Wheelabrator<br>
        <span style="color:#ef4444">&#9679;</span> Near Both (WB + I-95)<br>
        <span style="color:#f59e0b">&#9679;</span> I-95 Corridor Only<br>
        <span style="color:#6b7280">&#9679;</span> Control<br>
        <span style="color:#3b82f6">&#9679;</span> EPA AQS Monitor
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend))

    return Response(m._repr_html_(), mimetype="text/html")


@app.route("/api/emissions")
def api_emissions():
    """JSON API for emissions data."""
    df = get_emissions_df()
    return jsonify(df.to_dict(orient="records"))


if __name__ == "__main__":
    app.run(debug=True, port=5000)
